- README.md
This is similar to the changes in https://github.com/ddev/ddev-drupal-contrib/pull/7, but updating the steps to include the --create-docroot option.
> [docs] Clarifying need to use drupal project type

- README.md
When following the README Installation instructions for setting up a contrib project, additional setup is required before being able to run the commands provided by this project.
Explicitly list all steps needed for setup.
Review documentation changes.
N/A. Documentation update.
Related: https://github.com/ddev/ddev-drupal-contrib/issues/15
N/A
> Add additional steps needed to finish setup on contrib projects.

- commands/web/phpunit
This PR improves PHPunit configure-ablity. 
The idea being, if a repository has phpunit config file present, it will default to using it.
When running `ddev phpiunit`
If a `phpunit.xml` (PHPunit config file)  is present, it used it by default.
If a `phpunit.xml` is NOT present, it runs the command as currently set.
This PR allows developers to add and commit phpunit configuration which then can be used by default. These values could be added via CLI, but this become quite verbose if lots of settings are require (I was working on a module in a Gitpod workspace). 
While devlopers can take control of the command and make the required adjust, doing so prevents future updates.
> allow local phpunit config

- commands/web/symlink-project
This PR fixes an issue with projects that use 'underscores' in their name. 
- underscores are valid in machine names for Drupal modules, 
- underscores are invalid in hostnames.  
This can lead to inconsistency when using a project name as the sym-linked folder name.
I have a module named 'apple_banana'.
Drupal rules state machine name as "only lower-case letters, digits, and underscores" (https://www.drupal.org/docs/develop/creating-modules/naming-and-placing-your-drupal-module#s-name-your-module)
Given this module is in a directory called `apple_banana`, I am unable to create a DDEV project in this folder:
```shell
$ ddev config
Creating a new DDEV project config in the current directory 
...
Project name (apple_banana):
apple_banana is not a valid project name. Please enter a project …
```
> fix: symlink project with underscores instead of hyphens

- README.md
`phpcbf` can be automated before committing to fix coding standard violations.
The PHPCS repo that is currently linked to has been abandoned.
Add a guide with pre commit hook to automate phpcbf.
Provide a link to the new PHPCS repo.
Follow the guide to see if it is correct.
Enter the old repo link to see a banner informing about  the abandonment.
> Add guide to automatically run phpcbf, update link to PHPCS repo

- README.md
Just followed your discuss in #ddev channel and found the link to ddev-mkdocs added in this project was wrong.
> Fix ddev-mkdocs url

- commands/web/expand-composer-json
- commands/web/phpcbf
- commands/web/phpcs
- commands/web/symlink-project
Branch `1.0.x` in Gitlab templates has been deprecated and did not receive commits in 2 months.
Replace usage of `1.0.x` in URLs with the `default-ref` that is recommended.
https://www.drupal.org/project/gitlab_templates/issues/3404175
> Update script URLs to use the recommended default-ref

- README.md
- commands/web/expand-composer-json
- config.contrib.yaml
- tests/test.bats
Issue discussion at #38
This is my proposal for version detection. Default to 10 (until 11 is released), and ask user to override via ddev config as needed. No more looking at DDEV_PROJECT_TYPE.
I'm unsure how best to override the env variable that this project's config.contrib.yaml. Supplies. Can user do that in their project's config.yaml, or do they need to create a config.zz.yaml?
> Less smart Drupal core version detection

- commands/web/expand-composer-json
The 'drupal' ProjectType was introduced in ddev v1.23.0 and will eventually replace drupal8, drupal9, and drupal10 ProjectTypes.
This PR adds the 'drupal' ProjectType in the annotation.
#45 is where the change was originally made but was overlooked when closing the PR.
> Add 'drupal' ProjectType in expand-composer-json

- install.yaml
The current install.yaml uses `commands` in the project_files section. 
Unfortunately, that means that when the add-on is uninstalled, it will remove everything in the `commands` directory.
Using directories in `project_files` is OK if they're directories created/maintained by the add-on, but in this case, the directory is one that is shared more generally.
List the items in commands/web individually.
* Install the add-on and then remove it. It should not remove existing commands/web contents
You can install with `ddev get https://github.com/rfay/ddev-drupal-contrib/tarball/20240606_explicit_commands`
> fix: install.yaml needs to list commands separately to avoid removal of `commands` directory

- README.md
> DDEV project type is always 'drupal'

- commands/web/phpunit
The test output from `ddev phpunit` has the following problems:
- The previous exception is not shown, see https://github.com/sebastianbergmann/phpunit/issues/5863
- The "HTML output was generated" message from Drupal is not shown.
How does this happen?
Currently the `phpunit` command from this package calls phpunit with a `--testdox` parameter.
This parameter replaces the printer we previously set with `--printer`.
By removing the `--testdox` argument, we fall back to the Drupal output printer.
A developer can still manually append `--testdox` by running `ddev phpunit --testdox`, if they prefer that format.
In a project with the ddev-drupal-contrib extension, create a test case like this:
```php
use PHPUnit\Framework\TestCase;
class ExampleUnitTest extends TestCase {
public function …
```
> Remove `--testdox` parameter from phpunit command

- README.md
- commands/web/phpstan
- commands/web/poser
- install.yaml
- tests/test.bats
Adds support for `phpstan` command to more closely mimic [GitLab CI configuration/runs](https://git.drupalcode.org/search?search=phpstan&nav_source=navbar&project_id=96292&group_id=2&search_code=true&repository_ref=1.0.x).
* Adds the phpstan command.
* Updates README documentation to include command.
1. Run `ddev phpstan`
2. PHPStan should run as expected.
N/A
Closes https://github.com/ddev/ddev-drupal-contrib/issues/13
N/A
> Add phpstan command.

- README.md
I've been seeing a variety of support issues where composer doesn't work right because using php8.2 instead of 8.3. We've been proposing php8.3 for drupal10 and 11 for some time in the DDEV quickstarts.
Suggest php8.3 in the instructions instead of php8.2
> docs: Default to using php8.3 in README

- commands/web/eslint
- commands/web/stylelint
`ddev yarn --cwd web/core install` doesn't work with D11, it does the cwd but then fail as install is being run with v1.x.
Instead suggest `ddev exec "cd web/core && yarn install"` which should work for either version.
> fix: eslint/styleint not available error message

- commands/web/eslint
- commands/web/stylelint
thanks for merging #82 
This is a follow up as I was hardcoding something I shouldn't have.
> fix: use $DDEV_DOCROOT instead of hardcoded web/

- commands/web/eslint
> fix: eslint should replace dashes for underscore 

- README.md
- config.contrib.yaml
* https://github.com/ddev/ddev-drupal-contrib/issues/75
I moved the information on changing the core version to a separate section and rewrote it.  This is what worked for me, but I find it strange that the PHP_VERSION is set in .config.yaml, while the core version to override is set in .config.local.yaml.
> Improve documentation for how to change the version of Drupal core, fixes #75

- README.md
- config.contrib.yaml
- tests/_common.bash
- tests/full.bats
Drupal 11 is the main stable branch. This already happens in Drupal GitLab CI, see https://git.drupalcode.org/project/gitlab_templates/-/merge_requests/242
Installs by default with Drupal 11. 
On a contrib, configure DDEV with /ddev/ddev-drupal-contrib and run `ddev poser`. You should get a D11 site by default.
Should work
https://git.drupalcode.org/project/gitlab_templates/-/merge_requests/242
None.
> Drupal 11 is the main stable branch

- commands/web/eslint
GitLab Templates uses `core/.eslintrc.passing.json` configuration. Quoting from https://git.drupalcode.org/project/gitlab_templates/-/blob/main/docs/jobs/eslint.md?ref_type=heads#eslint
> Your project does not need a `.eslintrc.json` file because a default one matching Core's standards `core/.eslintrc.passing.json` is used. If you do create a `.eslintrc.json` file then it only needs to contain the specific rules that you want to override, because all other rules will be inherited due to ESLint's cascading configuration.
The `core/.eslintrc.passing.json` config includes/merges `core/.eslintrc.json` and `core/..eslintrc.jquery.json`.
But this add-on only uses `core/.eslintrc.json`, meaning `core/.eslintrc.jquery.json` is ignored. It happens that you test locally with `ddev eslint` but in CI …
> Use same ESLint config as GitLab

- commands/web/phpstan
In DDEV v1.24.0 (HEAD) the `drupal111` project type becomes "normal" for D11, and is autodetected in ddev-drupal-contrib tests.
The phpstan command provided by this add-on had a `# ProjectTypes: drupal,drupal8,drupal9,drupal10` which isn't very useful. (That directive is intended to not clog up the `ddev help` when using project types other than Drupal*)
Current [tests using DDEV HEAD](https://github.com/ddev/ddev-drupal-contrib/actions/runs/12065240371/job/33643600489) are failing with "# Command 'phpstan' is not available for the 'drupal11' project type."
Remove the ProjectTypes restriction on this one command. As with the rest of the commands in this add-on, it seems people would not have installed this add-on if they weren't using Drupal.
Install add-on
Restart
`ddev phpstan`
> fix: remove ProjectTypes from phpstan command

- commands/web/phpcbf
- commands/web/phpcs
phpcs and phpcs commands are using a hardcoding docroot.
Uses $DDEV_DOCROOT
Uses a docroot different than web/
> fix: use $DDEV_DOCROOT in phpcs and phpcbf commands

- README.md
- commands/web/symlink-project
- config.contrib.yaml
- tests/_common.bash
Symlinks are no more correctly created. This is caused by a GitLab Templates project change. See https://git.drupalcode.org/project/gitlab_templates/-/commit/e32e8cfd73bb570ea844ea560e8d46606dd196ca
Provides a missing env var
With main branch
- Remove everything under web/modules/custom
- Run `ddev symlink-project`
You should see the module created directly under `web/`. It should be under `web/modules/custom`.
With this branch repeat the operations and check that the correct symlink is created.
None.
N/A
None
> fix: adapt to https://git.drupalcode.org/project/gitlab_templates/-/commit/e32e8cf change

- commands/web/eslint
- commands/web/expand-composer-json
- commands/web/nightwatch
- commands/web/phpcbf
- commands/web/phpcs
- commands/web/phpstan
- commands/web/phpunit
- commands/web/poser
- commands/web/stylelint
- commands/web/symlink-project
`#!/bin/bash` doesn't work on NixOS.
Uses `#!/usr/bin/env bash` for commands.
> refactor: use `#!/usr/bin/env bash` instead of `#!/bin/bash`

- .github/workflows/tests.yml
- tests/_common.bash
Tests use `ddev get`.
Updates them to use `ddev add-on get`
> test: update bats to use `ddev add-on get`

- README.md
- commands/web/eslint
- commands/web/nightwatch
- commands/web/phpcbf
- commands/web/phpcs
- commands/web/phpstan
- commands/web/phpunit
- commands/web/stylelint
- commands/web/symlink-project
- config.contrib.yaml
- #111 
Leverage environment variable DRUPAL_PROJECTS_PATH in all custom ddev commands shipped with ddev-drupal-contrib.
Adds the following line to all commands:
```
DRUPAL_PROJECTS_PATH=${DRUPAL_PROJECTS_PATH:-modules/custom}
```
so that the $DRUPAL_PROJECTS_PATH environment variable can be used, if defined in `.ddev/config.local.yaml`, instead of the hardcoded fallback value `modules/custom`.
```bash
ddev add-on get https://github.com/jameswilson/ddev-drupal-contrib/tarball/111-env-var-project-path
```
Set a custom symlink location in .ddev/config.local.yaml
```yaml
web_environment:
- ...
- DRUPAL_PROJECTS_PATH=modules
```
Restart, re-symlink, then run one of the additional commands, eg `eslint` (if your module has custom js).
```bash
ddev restart
ddev symlink-project
ddev eslint
``` …
> feat: use DRUPAL_PROJECTS_PATH for all commands. fixes #111

- commands/web/nightwatch
- install.yaml
Because
* DDEV_APPROOT: Absolute path to the project files within the web container
* DDEV_DOCROOT: Relative path from approot to docroot
https://ddev.readthedocs.io/en/stable/users/extend/custom-commands/#environment-variables-provided
> Use DDEV_APPROOT instead

- README.md
- config.contrib.yaml
- install.yaml
- tests/_common.bash
to provide a full-flagged environment for running automated tests in contrib projects
-  Closes #124
> Add dependency on ddev/ddev-selenium-standalone-chrome

- commands/web/phpstan
> Fix PHPStan baseline generation

- README.md
- install.yaml
That dependency is going to have different major versions for different versions of Drupal core. Its better if contrib modules dont commit a given version of that dependency to their repos. So lets stop encouraging that so much with a formal dependency.
> Revert dependency on ddev/ddev-selenium-standalone-chrome
